// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBik-Eb2lsMhFJNnwuKurK-tRDVdGCCZFo',
    appId: '1:620700997033:web:2dc3585fe4bf085f6360b8',
    messagingSenderId: '620700997033',
    projectId: 'accounting-software-903a0',
    authDomain: 'accounting-software-903a0.firebaseapp.com',
    storageBucket: 'accounting-software-903a0.firebasestorage.app',
    measurementId: 'G-264VTHV04K',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBik-Eb2lsMhFJNnwuKurK-tRDVdGCCZFo',
    appId: '1:620700997033:web:a630ba38df4029896360b8',
    messagingSenderId: '620700997033',
    projectId: 'accounting-software-903a0',
    authDomain: 'accounting-software-903a0.firebaseapp.com',
    storageBucket: 'accounting-software-903a0.firebasestorage.app',
    measurementId: 'G-8KK78C1PQ2',
  );

}